### ISSUE TITLE
About the single model

### ISSUE THREAD

**Issue by skepsun** [zwt233/GAMLP#2]
It seems that "single GAMLP" actually refers to "GAMLP+0-RLU", which leverages label information. Maybe it is more fair to use GAMLP without "--use-rlu" as a single GAMLP to compare with other single models (without using label information).

**Comment by zwt233** [comment]
Thanks for your helpful advice. We will add an ablation study to test the performance of GAMLP without the label information as soon as possible. Note that RLU in our method is to enhance the original one-hot label with a more **reliable soft label** (parameterized by T). Once the soft label is available, we can use it in both label propagation and label distillation.  So, we assume a single GAMLP is the state that the predicted soft label is unavailable.

**Comment by zwt233** [comment]
> It seems that "single GAMLP" actually refers to "GAMLP+0-RLU", which leverages label information. Maybe it is more fair to use GAMLP without "--use-rlu" as a single GAMLP to compare with other single models (without using label information).

Thanks for your helpful advice. We will add an ablation study to test the performance of GAMLP without the label information as soon as possible. Note that RLU in our method is to enhance the original one-hot label with a more reliable soft label (parameterized by T). Once the soft label is available, we can use it in both label propagation and label distillation. So, we assume a single GAMLP is the state that the predicted soft label is unavailable.

**Comment by skepsun** [comment]
If a single GAMLP is the state that the predicted soft label is unavailable, then SAGN+0-SLE should also be included for single model comparison. The label model in SAGN+0-SLE and GAMLP (although you did not name it as the label model) should be the main reason for "very competitive" performance.

**Comment by zwt233** [comment]
> If a single GAMLP is the state that the predicted soft label is unavailable, then SAGN+0-SLE should also be included for single model comparison. The label model in SAGN+0-SLE and GAMLP (although you did not name it as the label model) should be the main reason for "very competitive" performance.

Thanks. We will add the comparison of SAGN+0-SLE as suggested.
