### ISSUE TITLE
The relations between GAMLP+RLU and SAGN+SLE

### ISSUE THREAD

**Issue by skepsun** [zwt233/GAMLP#3]
We are happy to see some improved work can be proposed based on our work SAGN+SLE. GAMLP seems to be designed as an extended version of SAGN with more kinds of attention mechanisms. And the main differences between RLU and SLE are the soft pseudo labels and KD loss, what we claim less useful in our paper (maybe they are actually useful, but need more experiments). Besides only citing SAGN +SLE in baseline, it is better to describe SAGN+SLE in Related Works and discuss the differences between SAGN+SLE and your GAMLP+RLU to highlight your unique contributions in your paper, since SAGN+SLE is a much more related and similar method than SGC, S2GC, SIGN and GBP, in terms of architecture, motivations and codes.

**Comment by zwt233** [comment]
> We are happy to see some improved work can be proposed based on our work SAGN+SLE. GAMLP seems to be designed as an extended version of SAGN with more kinds of attention mechanisms. And the main differences between RLU and SLE are the soft pseudo labels and KD loss, what we claim less useful in our paper (maybe they are actually useful, but need more experiments). Besides only citing SAGN +SLE in baseline, it is better to describe SAGN+SLE in Related Works and discuss the differences between SAGN+SLE and your GAMLP+SLE to highlight your unique contributions in your paper, since SAGN+SLE is a much more related and similar method than SGC, S2GC, SIGN and GBP, in terms of architecture, motivations and codes.

Thanks for your attention. The idea of using pseudo labels predicted by the classifier in RLU is indeed motivated by SLE . Besides, the concept of using an attention mechanism to assign a node-specific weight for different hops of propagated features is adapted from our previous work GMLP (https://arxiv.org/abs/2104.09880, see the adaptive aggregators in Section 3.3 and Figure 5).  We will add the comparison of SAGN in our related works as soon as possible.

**Comment by skepsun** [comment]
Thanks for your quick response! We agree that some effective and similar thoughts may be proposed during the same period.  And we appreciate the research about model degradation and more carefully designed attention mechanisms in your works! 

In addition, I have a small question. For ogbn-mag, does ComplEx act better than TransE?

**Comment by zwt233** [comment]
> Thanks for your quick response! We agree that some effective and similar thoughts may be proposed during the same period. And we appreciate the research about model degradation and more carefully designed attention mechanisms in your works!
> 
> In addition, I have a small question. For ogbn-mag, does ComplEx act better than TransE?

Thanks!  We did experiments and found that ComplEx indeed acted better than TransE in ogbn-mag. We are currently analyzing the influence of graph embedding algorithms on ogbn-mag, and we will show these results quickly.
